color:
  saturation: 0.2775365
  brandStrength: 0.09052182
  rhythmicContrast: 0.2720304
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  lightness: 0.004417157
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.04902218
typography_spectrum: 0.02661379
name: Exploring The World
